### ISSUE TITLE
SyntaxError: encrypt_data_channel=False cannot be used with a ftps:// url

### ISSUE THREAD

**Issue by liuyongcds** [sophiahjli/MitoRiboSeq#54]
Hi Sophia,
I have the problem when I run the snakemake. 
(MitoRiboSeq) ly@ly:/media/ly/11C368B83496F057/PDE21/MitoRiboSeq$ snakemake      -s code/mito_readphasing_metagene.snakefile      --configfile "code/mito_config.yml"      --use-conda      --cores 4

It report following error. Do you know what the problem is?

Kind regards,
Yong

SyntaxError:
encrypt_data_channel=False cannot be used with a ftps:// url
  File "/media/ly/11C368B83496F057/PDE21/MitoRiboSeq/code/mito_readphasing_metagene.snakefile", line 16, in <module>
  File "/media/ly/11C368B83496F057/PDE21/MitoRiboSeq/code/rules/genome.smk", line 15, in <module>
  File "/home/ly/miniconda3/envs/MitoRiboSeq/lib/python3.9/site-packages/snakemake/remote/FTP.py", line 70, in remote

**Comment by lparsons** [comment]
Thank you for taking the time to report this error. Unfortunately, [Snakemake doesn't support FTP with TLS](https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html#file-transfer-protocol-ftp). That means you won't be able to use an [`ftps://` url](https://en.wikipedia.org/wiki/FTPS) to automatically download the fasta file.

Instead, you can download the file manually and place it in the location specified by the [`genome_fasta_file` argument](https://github.com/sophiahjli/MitoRiboSeq/blob/master/code/mito_config.defaults.yml#L10) in the `code/mito_config.yml` file.

**Comment by lparsons** [comment]
Thank so much for your help in tracking down this bug. It appears this error is due to a [bug in newer versions of Snakemake](https://github.com/snakemake/snakemake/issues/1062#issue-930214541). Until the bug is fixed, a workaround would be to install version `6.3.0` or earlier of Snakemake. Please try:
```
conda activate MitoRiboSeq
conda install snakemake==6.3.0
```
Then try running the pipeline again.
