### ISSUE TITLE
Using a path with spaces can cause problems with conda packages

### ISSUE THREAD

**Issue by lparsons** [sophiahjli/MitoRiboSeq#55]
Using a path with spaces can cause issues with some conda packages. Despite the issue being closed (https://github.com/conda/conda/issues/638), some users (thanks @liuyongdk) have reported the error with cutadapt:
```
/bin/bash: /file/path/with spaces/MitoRiboSeq/.snakemake/conda/e0da449bafef2b3beda794d561cc2283/bin/cutadapt:
/file/path/with: bad interpreter: No such file or directory
```

**Comment by steffuhkneeuh** [comment]
What should someone do if they can't avoid spaces? For example the username includes a space, so changing that directory name might mess with every other installed application.

**Comment by lparsons** [comment]
I'm sorry, but since this appears to an issue with conda and/or how Snakemake uses conda, I don't have a good answer. One suggestion might be to install MitoRiboSeq outside of the user home directory, assuming you have permissions to do that on the machine.
